### ISSUE TITLE
LD.exe fails with undefined reference to __imp_* (ncurses library)

### ISSUE THREAD

**Issue by TSBower** [dungeons-of-moria/umoria#80] opened 2024-03-25 15:12 UTC
Using the MSYS2 environment, with the MINGW64 shell. Install the toolchain and cmake using pacman. Included ncurses library is version 6.4.x. Compilation is uneventful, but linker fails with several dozen "undefined reference to __imp_<function name>".

One of the headers in the ncurses library has dllexport defined, unless the -DNCURSES_STATIC is explicitly provided as a command line option. I manually added this flag into the CMakeLists.txt file, near the bottom (line 260) in the section where it comments # Make the ncurses library static. Not sure if this is the best place for it.

Recommend: update the project to ensure ncurses library links correctly static, or revise the readme to direct the user to a current environment that works OOtB.

**Comment by mrcook** [comment] 2024-04-01 14:42
Thanks @TSBower, unfortunately since I updated to an Arm macbook I no longer have the ability to run Windows. If you'd like to create a PR, I'd be happy to merge it.

**Comment by nhomble** [comment] 2024-12-09 02:47
I just got burned by this too.

@TSBower I think we arrived at the same solution: https://github.com/dungeons-of-moria/umoria/pull/90

Confirmed this works with mingw64.

**Comment by mrcook** [comment] 2024-12-09 21:41
Hi @TSBower , this should now be fixed with the PR from @nhomble . If there's still a problem, please do reopen this issue.

**Closed by mrcook** 2024-12-09 21:41 UTC
